#!/bin/bash

music() {
LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"
EWW_BIN="/usr/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/misc open --screen 0 music_win 
}

# Open widgets
if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww/misc close system calendar
    touch "$LOCK_FILE_SONG"
    run && echo "ok good!"
else
    ${EWW_BIN} -c $HOME/.config/eww/misc close music_win
    rm "$LOCK_FILE_SONG" && echo "closed"
fi
}


if [ "$1" = "music" ]; then
music
# elif [ "$1" = "system" ]; then
# system
# elif [ "$1" = "music" ]; then
# music
# elif [ "$1" = "audio" ]; then
# audio
fi
