import:
  # uncomment the flavour you want below:
#  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
  #- ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
  - ~/.config/alacritty/tokyonight_storm.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
window:
  opacity: 0.95

font:
  normal:
    family: JetBrainsMono Nerd Font Propo
  size: 12.0

shell:
    program: /usr/bin/zsh
    args:
    - -l
    - -c
    - "tmux"
